openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore Draft
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: 'todo'
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: 'todo'
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: 'todo'
          headers:
            x-next:
              description: 'todo'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: 'todo'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: 'todo'
      operationId: createPets
      tags:
        - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '201':
          description: 'todo'
        default:
          description: 'todo'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets/{petId}:
    get:
      summary: 'todo'
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: 'todo'
          schema:
            type: string
      responses:
        '200':
          description: 'todo'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: 'todo'
        '404':
          description: 'todo'
        default:
          description: 'todo'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Pet'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string